GET  http://localhost:1234/boocks
###
GET  http://localhost:1234/boocks/55
###
GET  http://localhost:1234/boocks?categor=Networking
###
POST http://localhost:1234/boock/
Content-Type: application/json

{
    "name": "100 años de soledad",
    "type":"normal",
    "movies":[
        "transform"
    ]
}