GET  http://localhost:1234/videoGamesaa
###
GET  http://localhost:1234/videoGames/publishers
###
GET  http://localhost:1234/videoGames?publisher=UBISOft
###
GET  http://localhost:1234/videoGames/developers
###
GET  http://localhost:1234/videoGames?developer=Crate Entertainment
###
POST http://localhost:1234/videoGames/developers
    Content-Type: application/json

    {
        "name": "diego Amachi"
    }
###
GET  http://localhost:1234/videoGames/56514712-a2d5-44a9-9b28-5bd930b487feaaa
###
GET  http://localhost:1234/videoGames?genre=Family
###
POST http://localhost:1234/videoGames
Content-Type: application/json

{
    "title": "ARK: Survival Of The Fittes",
        "genres": [1, 2, 3, 4, 5, 6],
        "publisher": 1,
        "description": "ARK: Survival of the Fittest is a Multiplayer Online Survival Arena (MOSA) game that pits as many as 72 combatants against one another in the struggle for survival in a harsh, changing environment packed with deadly creatures, &#x201C;Evolution Events,&#x201D; and other players.",
        "developer": 1,
        "coverImage": "https://steamcdn-a.akamaihd.net/steam/apps/407530/header.jpg?t=1567712233"
   
}
### Actualizar una pelicula 

PATCH  http://localhost:1234/videoGames/4e2bbcf5-b9ea-40ff-97fe-b0d3f11bc9a6
Content-Type: application/json

    {
        "publisher":4
    }
###

DELETE   http://localhost:1234/videoGames/0af43d92-81c5-4622-87bb-b6c17beec22b